# ========= global settings ===================================================
is_fullscreen: &fullscreen false
show_progress_bar: true
screenwidth: 1024
fontsize: &fontsize 20px
remove_prompt_below: &rr false
true_random: &tr true
prob_win: &pw .6
#max_time_allowed: 10 # Maximum time allowed for each participant in seconds

# ========= osf/datapipe/prolific settings ======================================
osf_id: jf8sc
prolific_id: 84F912E7
pipe_data_to_osf: true

# ========= practice settings ===================================================
practice_trial_rounds: &ptr 3
practice_trial_time: &ptt 5
show_practice_result: &pts false
number_of_history_keypress: &nhk 10

# ========= bonus settings ======================================================
bonus_trial_rounds: &btr 0
bonus_target_minimum: &btm 3
quantile_practice_scores_as_target:  &qpt 100 #use maximum
time:
  bonus_trial_time: &btt 5
  fixation_duration: &ffd 2
  feedback_score_time: &fst 0
  feedback_bonus_time: &fbt 0
target_number_dist: &btd 
  choice: uniform
  quantile: *qpt
  normal: {std: 20}
  uniform: {range: 20}
stop_when_pass_target: &swpt false

# ========= thank you message ===================================================
thank_you_msg: >
  <div align='center' style="margin: 10%">
      <p>Thank you for participating!</p>
      <br>
      <b>Please wait to be redirected to Prolific.</b>
  </div>

# ========= stimulus simulation =================================================
list_of_available_pair_keys: &llll 
  - a,b
  - c,d
  - a,s

# fullscreen
fullscreen:
  type: fullscreen
  fullscreen_mode: *fullscreen # doesn't work in MAC
  message: <p>The experiment will switch to full screen mode when you press the button below.</p>

# practice round
practice:
  numOfTrial: *ptr
  trial_duration: *ptt
  num_keypress_display: *nhk
  fixation_duration: *ffd #2 sec for guideline and 1 sec for fixation
  fontsize: *fontsize  #fontsize of displayed stimulus
  no_prompt: *rr
  show_stat: *pts
  data: 
    phase: practice
  list: *llll
  true_random: *tr
  prob_win: *pw
  max_time_allowed: 30  # Maximum time allowed for each participant in seconds

bonus_feedback_main: &bfm >
  <div class="bonus-1" style="margin: 40px 0px">
    <div class="bonus-2">
      <div class="bonus-3">Your score:</div>
      <div class="bonus-4"><span id="current-number">212</span></div>
    </div>
    <div class="bonus-2">
      <div class="bonus-3">Target score:</div>
      <div class="bonus-4" style="color: red"><span id="target-number">200</span></div>
    </div>
  </div>

bonus_feedback_success: &bfs >
  <div class="bonus-1" id="feedback">
    <div class="bonus-2">
      You reached the target score!
    </div>
    <div class="bonus-2">
      <div id="bonus-number"></div>
    </div>
  </div>

bonus_feedback_failure: &bff >
  <div class="bonus-1" id="feedback">
    <div class="bonus-2">
      You missed the target score!
    </div>
    <div class="bonus-2">
      <div id="bonus-number"></div>
    </div>
  </div>

bonus:
  numOfTrial: *btr
  target_dist: *btd
  target_min: *btm
  fontsize: *fontsize
  no_prompt: *rr
  time:
    trial_time: *btt
    fix_time: *ffd
    score_time: *fst
    reward_time: *fbt
  data: 
    phase: bonus
  list: *llll
  feedback:
    main_feedback: *bfm
    success_feedback: *bfs
    failure_feedback: *bff
  early_stop: *swpt
  true_random: *tr
  prob_win: *pw
  max_time_allowed: 30  # Maximum time allowed for each participant in seconds

# preload images
images_to_preload:
  type: preload
  data: 
    phase: preload
  images:
    - 

# consent pages

consent_page: &p1 >
  <div class='instruction'> 
  <h2 class='jspsych-content'>Welcome</h2>
  <dl>
      <dt>Purpose</dt>
      <dd>The purpose of this study is to determine how comfortable different pairs of keys are to type on computer keyboards to inform the design of future keyboard layouts.</dd>

      <dt>Procedures</dt>
      <dd>If you choose to participate, you will be repeatedly asked to type two new pairs of keys and report which pair is more comfortable to type. </dd>

      <dt>Risks</dt>
      <dd>There are no anticipated risks or discomforts from this research that you would not normally have when typing on your own keyboard.</dd>

      <dt>Benefits</dt>
      <dd>There are no anticipated benefits to you from this research.</dd>

      <dt>Compensation</dt>
      <dd>If you decide to participate, you will be compensated for your participation.</dd>

      <dt>Participation</dt>
      <dd>Taking part or not in this research study is your decision. You can decide to participate and then change your mind at any point.</dd>

      <dt>Contact Information</dt>
      <dd>If you have any questions about the purpose, procedures, or any other issues related to this research study you may contact the Principal Investigator, Dr. Arno Klein, at arno.klein@childmind.org. </dd>
  </dl>
  </div>

consent:
  type: checkbox
  data: 
    phase: consent
  questions:
    - prompt: *p1
      timing_post_trial: 0
      options: ["I have read and understand the information in this form and I agree to participate in the study. I am 18 years of age or older. I have been given the opportunity to ask any questions I had and those questions have been answered to my satisfaction. I understand that I can print or request a copy of this form for my records"]
      required: true
  required_message: To proceed to the experiment, please ensure that you have checked the checkboxes above.
  button_label: Next